// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR7IgIVNwIaLaVUtswFlwtDNwE1aMOuRo',
    appId: '1:193034358656:web:7ee062a70415e121d8fb65',
    messagingSenderId: '193034358656',
    projectId: 'project-mad-gimjungwook',
    authDomain: 'project-mad-gimjungwook.firebaseapp.com',
    storageBucket: 'project-mad-gimjungwook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuL1McR4kXNgAkQVpKzS5n_qW_C71Byak',
    appId: '1:193034358656:android:7a075268527829a2d8fb65',
    messagingSenderId: '193034358656',
    projectId: 'project-mad-gimjungwook',
    storageBucket: 'project-mad-gimjungwook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhwWBOWQfZGrUpdA0ZoJlOdKymq6FjtQ',
    appId: '1:193034358656:ios:2578de42b0981785d8fb65',
    messagingSenderId: '193034358656',
    projectId: 'project-mad-gimjungwook',
    storageBucket: 'project-mad-gimjungwook.firebasestorage.app',
    iosBundleId: 'gimjungwook.final.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArhwWBOWQfZGrUpdA0ZoJlOdKymq6FjtQ',
    appId: '1:193034358656:ios:e5f6bf2367357a93d8fb65',
    messagingSenderId: '193034358656',
    projectId: 'project-mad-gimjungwook',
    storageBucket: 'project-mad-gimjungwook.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR7IgIVNwIaLaVUtswFlwtDNwE1aMOuRo',
    appId: '1:193034358656:web:994cab864765ef0bd8fb65',
    messagingSenderId: '193034358656',
    projectId: 'project-mad-gimjungwook',
    authDomain: 'project-mad-gimjungwook.firebaseapp.com',
    storageBucket: 'project-mad-gimjungwook.firebasestorage.app',
  );
}
